### ISSUE TITLE
C++ 推理导出的pose engine文件，输入也需要是pytorch的tensor吗

### ISSUE THREAD

**Issue by lofyol** [Gwencong/yolo-pose-escalator#5]

**Comment by Gwencong** [comment]
不是的，在代码里输入为pytorch tensor是因为我使用pytorch将数据拷贝到GPU上。用python写推理代码时，实际上输入一般为numpy 数组（cv2.imread读取图片），然后在进行数据拷贝到GPU时，用pytorch进行拷贝的话就要把numpy 数组先转成tensor，如果使用pycuda或者cuda-python拷贝数据则使用他们对应的函数。

**Comment by lofyol** [comment]
好的谢谢解答，另外一个就是C++ TRT推理情况下，efficientNMS是要求了tensorrt版本大于8.2吗

**Comment by Gwencong** [comment]
这个要看tensorrt什么时候加入了这个算子，好像是[8.0](https://github.com/NVIDIA/TensorRT/tree/release/8.0/plugin/efficientNMSPlugin)就有这个plugin了，如果低版本没有这个plugin，应该也可以自己拿它的源代码编译
