### ISSUE TITLE
Can I have the pt file

### ISSUE THREAD

**Issue by PredyDaddy** [Gwencong/yolo-pose-escalator#9]
## ❔Question
Hello, Could you provide the yolov5l6_pose.pt, I just couldn't find it.  Many many thanks.

**Comment by PredyDaddy** [comment]
大佬您好，是这样的，我去原来的yolo-pose的仓库看他的pre-tainedmodel已经不能用了，我想从你这边拿一个yolo-pose的pt文件或者onnx文件可以吗？

**Comment by Gwencong** [comment]
yolo-pose的仓库的预训练模型还可以用呀，源码地址[https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose](https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose)，你可以下载这个 [yolov5l6_960](http://software-dl.ti.com/jacinto7/esd/modelzoo/gplv3/08_02_00_11/edgeai-yolov5/pretrained_models/checkpoints/keypoint/coco/edgeai-yolov5/other/best_models/yolov5l6_960_69p6_90p1_kpts_head_6x_dwconv_3x3_lr_0p01/weights/last.pt)，复制链接地址，然后在chrome中新建标签粘贴地址打开下载，chrome里直接点击链接好像没反应

**Comment by PredyDaddy** [comment]
谢谢大佬
